[package]
name = "rustlebrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
open = "1.7.0"
rayon = "1.5.1"
colorgrad = "0.6.2"

[profile.release]
opt-level = 3
